
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 658)
        MainWindow.setStyleSheet("/*\n"
"ABOUT\n"
"===========================================================\n"
"version 1.7a\n"
"QT theme (stylesheet) specially developed for FreeCAD (http://www.freecadweb.org/).\n"
"It might work with other software that uses QT styling.\n"
"\n"
"\n"
"LICENSE\n"
"===========================================================\n"
"Copyright (c) 2015 Pablo Gil Fernández\n"
"The stylesheet barely uses code from Colin Duquesnoy \"generic QT stylesheet\"\n"
"\n"
"This work is licensed under the Creative Commons Attribution-ShareAlike 4.0 International License.\n"
"To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/4.0/.\n"
"\n"
" \n"
"\n"
"CUSTOMIZATION\n"
"===========================================================\n"
"If you would like to change the overall look/style of the theme, just find and replace following colors in the whole file:\n"
"    background darker = #828282\n"
"    background dark and slighly darker = #a2a2a0\n"
"    background dark = #b6b6b6\n"
"    background normal and slighly darker = #e0e0e0\n"
"    background normal = #e6e6e6\n"
"    background light = #f5f5f5\n"
"    background lighter = #ffffff\n"
"\n"
"    lists background = #bdc1c9\n"
"    lists background (alternate) = #b3b8bf\n"
"    lists backgrounds selection = #abb0b7\n"
"\n"
"    foreground = black\n"
"\n"
"    selection darker = #1b3774\n"
"    selection dark = #3874f2\n"
"    selection normal = #5e90fa\n"
"    selection inbetween normal and light = #6f9efa (used to build SpinBoxes)\n"
"    selection light = #7cabf9\n"
"    selection lighter = #adc5ed\n"
" \n"
"*/\n"
"\n"
"/* RESET EVERYTHING */\n"
"QAbstractScrollArea,QCheckBox,QColumnView,QComboBox,QDateEdit,QDateTimeEdit,QDialog,QDialogButtonBox,QDockWidget,QDoubleSpinBox,QFrame,QGroupBox,QHeaderView,QLabel,QLineEdit,QListView,QListWidget,QMainWindow,QMenu,QMenuBar,QMessageBox,QProgressBar,QPushButton,QRadioButton,QScrollBar,QSizeGrip,QSlider,QSpinBox,QSplitter,QStatusBar,QTabBar,QTabWidget,QTableView,QTableWidget,QTextEdit,QTimeEdit,QToolBar,QToolButton,QToolBox,QToolTip,QTreeView,QTreeWidget,QWidget {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border: 0px;\n"
"    border-style: none;\n"
"    background-color: #e6e6e6; /* set with default background color */\n"
"}\n"
"\n"
"QMdiArea[showImage=\"true\"] {\n"
"    background-image: url(icons/background_freecad.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"\n"
"QProgressBar,\n"
"QProgressBar:horizontal {\n"
"    background: #bdc1c9;\n"
"    border: 1px solid #b6b6b6;\n"
"    text-align: center;\n"
"    padding: 1px;\n"
"    border-radius: 4px;\n"
"}\n"
"QProgressBar::chunk,\n"
"QProgressBar::chunk:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: #828282;\n"
"    color: black;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QWidget {\n"
"    color: #828282;\n"
"    background-color: #e6e6e6;\n"
"    background-clip: border;\n"
"    border-image: none;\n"
"    outline: 0;\n"
"}\n"
"\n"
"QWidget:focus {\n"
"    border: 1px solid #828282;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"    color: #f5f5f5;\n"
"    background-color: #828282; /* same as QMenu background-color */\n"
"}\n"
"\n"
"QMenuBar {\n"
"    color: #ffffff;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    color: #1b3774;\n"
"    border: 1px solid #5e90fa;\n"
"    background-color: #5e90fa;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"    color: #1b3774;\n"
"    border: 1px solid #7cabf9;\n"
"    background-color: #7cabf9;\n"
"    margin-bottom:-1px;\n"
"    padding-bottom:1px;\n"
"}\n"
"\n"
"QMenu {\n"
"    color: #ffffff;\n"
"    background-color: #828282;\n"
"    margin: 2px;\n"
"    border: 1px solid transparent;\n"
"}\n"
"\n"
"QMenu::icon {\n"
"    margin: 5px;\n"
"    border-style: none;\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
"    image:url(icons/right_arrow_light.png);\n"
"}\n"
"\n"
"QMenu::item {\n"
"    color: #ffffff;\n"
"    background-color: #828282;\n"
"    padding: 2px 30px 2px 30px;\n"
"    border: 1px solid #828282; /* reserve space for selection border */\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    color: #1b3774;\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    height: 1px;\n"
"    background-color: #b6b6b6;\n"
"    margin-top: 2px;\n"
"    margin-bottom: 2px;\n"
"    margin-left: 6px;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive {\n"
"    color: #ffffff;\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #828282;\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius:2px;\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image:url(icons/checkbox_light.png);\n"
"}\n"
"\n"
"QGroupBox {\n"
"    color: #828282;\n"
"    font-weight: bold;\n"
"    border:1px solid blue;\n"
"    border-radius: 4px;\n"
"    margin-top: 20px;\n"
"    border-color: rgba(0, 0, 0, 20); /* lighter than \"QGroupBox\" border-color */\n"
"    background-color: rgba(255, 255, 255, 15);\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding-left: 10px;\n"
"    padding-right: 10px;\n"
"    padding-top: 10px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractScrollArea {\n"
"    border-radius: 2px;\n"
"    border: 1px solid #3A3939;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractScrollArea::corner {\n"
"    border: none;\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    height: 15px;\n"
"    margin: 3px 15px 3px 15px;\n"
"    border: 1px transparent #828282;\n"
"    border-radius: 4px;\n"
"    background-color: #828282;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #b6b6b6;\n"
"    min-width: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    margin: 1px 3px 0px 3px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/right_arrow_light.png);\n"
"    width: 6px;\n"
"    height: 10px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    margin: 1px 3px 0px 3px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/left_arrow_light.png);\n"
"    height: 10px;\n"
"    width: 6px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover,\n"
"QScrollBar::add-line:horizontal:on {\n"
"    border-image: url(icons/right_arrow_lighter.png);\n"
"}\n"
"\n"
"\n"
"QScrollBar::sub-line:horizontal:hover,\n"
"QScrollBar::sub-line:horizontal:on {\n"
"    border-image: url(icons/left_arrow_lighter.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal,\n"
"QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: #828282;\n"
"    width: 15px;\n"
"    margin: 15px 3px 15px 3px;\n"
"    border: 1px transparent #828282;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background-color: #b6b6b6;\n"
"    min-height: 5px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    margin: 3px 0px 3px 1px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/up_arrow_light.png);\n"
"    height: 6px;\n"
"    width: 10px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    margin: 3px 0px 3px 1px; /* 1px to correctly fit the 10px width image */\n"
"    border-image: url(icons/down_arrow_light.png);\n"
"    height: 6px;\n"
"    width: 10px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover,\n"
"QScrollBar::sub-line:vertical:on {\n"
"    border-image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover,\n"
"QScrollBar::add-line:vertical:on {\n"
"    border-image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit {\n"
"    color: #828282;\n"
"    background-color: #bdc1c9;\n"
"    border: 1px solid #b6b6b6;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    color: #828282;\n"
"    background-color: #bdc1c9;\n"
"    border-radius: 2px;\n"
"    border: 1px solid #b6b6b6;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSizeGrip {\n"
"    image: url(icons/sizegrip_light.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QRadioButton::indicator:unchecked{\n"
"    color: #828282;\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #828282;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image:url(icons/radiobutton_light.png);\n"
"}\n"
"\n"
"QCheckBox,\n"
"QRadioButton,\n"
"QCheckBox:disabled,\n"
"QRadioButton:disabled {\n"
"    color: #828282;\n"
"    padding: 3px;\n"
"    outline: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QGroupBox::indicator {\n"
"    color: #ffffff;\n"
"    background-color: #f5f5f5;\n"
"    border: 1px solid #828282;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius:2px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 11px;\n"
"    height: 11px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QRadioButton::indicator:pressed,\n"
"QCheckBox::indicator:pressed,\n"
"QCheckBox::indicator:non-exclusive:checked:pressed,\n"
"QCheckBox::indicator:indeterminate:pressed,\n"
"QCheckBox::indicator:checked:pressed {\n"
"    border-color: #adc5ed;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked,\n"
"QGroupBox::indicator:checked {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image:url(icons/checkbox_light.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled,\n"
"QRadioButton::indicator:disabled {\n"
"    border: 1px solid #b6b6b6;\n"
"}\n"
"\n"
"QCheckBox:disabled,\n"
"QRadioButton::indicator:disabled {\n"
"    color: #b6b6b6;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled,\n"
"QGroupBox::indicator:disabled,\n"
"QMenu::indicator:non-exclusive:disabled {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"    background-color: #3874f2;\n"
"    border: 1px solid #1b3774;\n"
"    image: url(icons/checkbox_indeterminate_light.png);\n"
"}\n"
"\n"
"QCheckBox:focus,\n"
"QRadioButton:focus {\n"
"    border: none;\n"
"}\n"
"\n"
"QFrame,\n"
"QFrame:pressed,\n"
"QFrame:focus,\n"
"QFrame:on {\n"
"    border: 1px solid #e6e6e6;\n"
"    border-radius: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* border and background of QComboBox drop-down */\n"
"QComboBox QFrame,\n"
"QComboBox QFrame:pressed,\n"
"QComboBox QFrame:focus,\n"
"QComboBox QFrame:on {\n"
"    border: 1px solid #828282;\n"
"    background-color: #828282;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QFrame[frameShape=\"0\"] {\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QFrame[height=\"3\"],\n"
"QFrame[width=\"3\"] {\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QFrame[height=\"3\"] {\n"
"    border-top-color: #b6b6b6;\n"
"}\n"
"\n"
"QFrame[width=\"3\"] {\n"
"    border-left-color: #b6b6b6;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #b6b6b6, stop:1 #e6e6e6);\n"
"    border: 1px solid #828282;\n"
"    padding: 5px 12px 5px 12px;\n"
"    margin: 4px 8px 4px 8px;\n"
"    border-radius: 3px;\n"
"    min-width: 14px;\n"
"    min-height: 14px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QPushButton:focus {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QPushButton:disabled,\n"
"QPushButton:disabled:checked {\n"
"    color: #b6b6b6;\n"
"    background-color: #e6e6e6;\n"
"    border-color: #b6b6b6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3874f2;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: #5e90fa;\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"/* Color Buttons */\n"
"Gui--ColorButton,\n"
"Gui--ColorButton:disabled {\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"    height: 24px;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"Gui--ColorButton:hover {\n"
"    border-color: #e0e0e0;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"/* Buttons inside the toolbar */\n"
"QToolBar QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #e0e0e0, stop:1 #e6e6e6);\n"
"    border: 1px solid #b6b6b6;\n"
"    min-width: 22px;\n"
"    min-height: 22px;\n"
"    margin-left: 2px;\n"
"    margin-right: 2px;\n"
"    margin-bottom: 3px; /*bigger margin to correctly separate buttons inside a vertical toolbar */\n"
"    margin-top: 1px;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QToolBar QPushButton:hover,\n"
"QToolBar QPushButton:focus {\n"
"    color: #ffffff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #e0e0e0, stop:1 #e6e6e6);\n"
"    border: 1px solid #828282;\n"
"}\n"
"\n"
"QToolBar QPushButton:disabled,\n"
"QToolBar QPushButton:disabled:checked {\n"
"    background-color: #e6e6e6;\n"
"    border-color: #e0e0e0;\n"
"}\n"
"\n"
"QToolBar QPushButton:pressed {\n"
"    background-color: #b6b6b6;\n"
"    border-color: #b6b6b6;\n"
"}\n"
"\n"
"QToolBar QPushButton:checked {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9);\n"
"    border-color: #5e90fa;\n"
"}\n"
"\n"
"QToolBar QPushButton:checked:hover,\n"
"QToolBar QPushButton:checked:focus {\n"
"    color: #ffffff;\n"
"    border: 1px solid #3874f2;\n"
"}\n"
"\n"
"QToolBar {\n"
"    border: 1px transparent #393838;\n"
"    background-color: #e6e6e6;\n"
"    font-weight: bold;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"    background-image: url(icons/Hmovetoolbar_dark.png);\n"
"    width: 10px;\n"
"    margin: 6px 2px 6px 2px;\n"
"    background-position: top right;\n"
"    background-repeat: repeat-y;\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"    background-image: url(icons/Vmovetoolbar_dark.png);\n"
"    height: 10px;\n"
"    margin: 2px 6px 2px 6px;\n"
"    background-position: left bottom;\n"
"    background-repeat: repeat-x;\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"    background-image: url(icons/separtoolbar_dark.png);\n"
"    width: 10px;\n"
"    margin: 6px 2px 6px 2px;\n"
"    background-position: center center;\n"
"    background-repeat: repeat-y;\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"    background-image: url(icons/separtoolbar_dark.png);\n"
"    height: 10px;\n"
"    margin: 2px 6px 2px 6px;\n"
"    background-position: center center;\n"
"    background-repeat: repeat-x;\n"
"}\n"
"\n"
"QStackedWidget {\n"
"    background-color: #e6e6e6;\n"
"    border: 1px transparent #e6e6e6;\n"
"}\n"
"\n"
"QAbstractSpinBox {\n"
"    color: #ffffff;\n"
"    border: 1px solid #b6b6b6; /* border top color defined after QAbstractSpinBox, QLineEdit and QComboBox */\n"
"    background-color: #b6b6b6;\n"
"    selection-color: black;\n"
"    selection-background-color: #5e90fa;\n"
"}\n"
"\n"
"QAbstractSpinBox:disabled {\n"
"    color: #f5f5f5;\n"
"    background-color: #e0e0e0;\n"
"    border-color: #e0e0e0;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #6f9efa, stop:1 #7cabf9);\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: top right;\n"
"    border-top-right-radius: 3px;\n"
"    height: 13px;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #6f9efa);\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: bottom right;\n"
"    border-bottom-right-radius: 3px;\n"
"    height: 13px;\n"
"    width: 20px;\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button:disabled,\n"
"QAbstractSpinBox:down-button:disabled {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow {\n"
"    image: url(icons/up_arrow_light.png);\n"
"    top: 0px; /* fix simetry between up and down images */\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:hover {\n"
"    image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:off {\n"
"    image: url(icons/up_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:disabled {\n"
"    image: none;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow {\n"
"    image: url(icons/down_arrow_light.png);\n"
"    bottom: -2px; /* fix simetry between up and down images */\n"
"}\n"
"QAbstractSpinBox::down-arrow:hover {\n"
"    image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:off {\n"
"    image: url(icons/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:disabled {\n"
"    image: none;\n"
"}\n"
"\n"
"QToolBar QAbstractSpinBox {\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    color: #ffffff;\n"
"    background-color: #b6b6b6;\n"
"    selection-color: black;\n"
"    selection-background-color: #5e90fa;\n"
"    /* Padding and margin defined */\n"
"    border-style: solid;\n"
"    border: 1px solid #b6b6b6; /* border top color defined after QAbstractSpinBox, QLineEdit and QComboBox */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QAbstractSpinBox:focus,\n"
"QLineEdit:focus,\n"
"QComboBox:focus {\n"
"    border-color: #7cabf9;\n"
"}\n"
"\n"
"QComboBox {\n"
"    color: #ffffff;\n"
"    background-color: #b6b6b6;\n"
"    selection-color: black;\n"
"    selection-background-color: #5e90fa;\n"
"    border: 1px solid #b6b6b6; /* border top color defined after QAbstractSpinBox, QLineEdit and QComboBox */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    color: black;\n"
"    background-color: #b6b6b6;\n"
"    border-color: #7cabf9;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top right;\n"
"    width: 20px;\n"
"    border-left-width: 1px;\n"
"    border-left-color: transparent;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.8, x2:1, y2:0, stop:0 #5e90fa, stop:1 #7cabf9);\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(icons/down_arrow_light.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #ffffff;\n"
"    background-color: #828282;\n"
"    border-radius: 3px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Common parameters for QAbstractSpinBox, QLineEdit and QComboBox */\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QAbstractSpinBox,\n"
"QLineEdit,\n"
"QComboBox {\n"
"    border-top-color: #a2a2a0; /* Creates an inset effect inside the elements */\n"
"    padding: 2px 6px 2px 6px; /* This makes text colour work on QComboBox */\n"
"    margin: 0px 2px 0px 2px;\n"
"    min-width: 70px; /* it was 120 because of QCombobox... */\n"
"    border-radius: 3px;\n"
"}\n"
"/* end Common parameters */\n"
"\n"
"QAbstractItemView {\n"
"    color: #828282;\n"
"    alternate-background-color: #b3b8bf; /* related with QListView background  */\n"
"    border: 1px solid #828282;\n"
"    border-radius: 3px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"/* hack to deactivate changing background color when focus (due to QFrame generic transparent color) */\n"
"QAbstractItemView:selected,\n"
"QAbstractItemView:on,\n"
"QAbstractItemView:focus {\n"
"    background-color: #bdc1c9; /* same as QTable background color */\n"
"}\n"
"\n"
"/* hack to hide weird redundant information inside the value of a Placement cell */\n"
"QTreeView QLabel,\n"
"QTreeView QLabel:disabled {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QTreeView QLineEdit {\n"
"    color: #ffffff;\n"
"    border-color: #b6b6b6;\n"
"    background-color: #b6b6b6;\n"
"    selection-color: black;\n"
"    selection-background-color: #5e90fa;\n"
"}\n"
"\n"
"/* hack to hide non editable cells inside Property values */\n"
"QTreeView QLineEdit:read-only,\n"
"QTreeView QLineEdit:disabled,\n"
"QTreeView QAbstractSpinBox:read-only,\n"
"QTreeView QAbstractSpinBox:disabled {\n"
"    color: transparent;\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"    selection-color: transparent;\n"
"    selection-background-color: transparent;\n"
"}\n"
"\n"
"/* hack to disable margin inside Property values to following elements */\n"
"QTreeView QSpinBox,\n"
"QTreeView QDoubleSpinBox,\n"
"QTreeView QAbstractSpinBox,\n"
"QTreeView QLineEdit,\n"
"QTreeView QComboBox {\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"}\n"
"\n"
"/* Pushbutton style for \"...\" inside Placement cell which launches Placement tool */\n"
"QTreeView QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #b6b6b6, stop:1 #e6e6e6);\n"
"    border-top: none;\n"
"    border-bottom: none;\n"
"    border-right: none;\n"
"    border-left: 1px solid #b6b6b6;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    height: 24px;\n"
"}\n"
"\n"
"/* Color Buttons inside the \"Properties window\" */\n"
"QAbstractItemView Gui--ColorButton {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    height: 10px;\n"
"}\n"
"\n"
"QAbstractItemView QPushButton:hover {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QAbstractItemView QPushButton:disabled {\n"
"    color: transparent;\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"QLabel {\n"
"    border: 0px solid #828282;\n"
"}\n"
"\n"
"QTabWidget{\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget:focus {\n"
"    border: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: none;\n"
"    padding: 0px;\n"
"    background-color: #e6e6e6;\n"
"    position: absolute;\n"
"    top: -15px;\n"
"    padding-top: 15px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar {\n"
"    qproperty-drawBase: 0;\n"
"    left: 5px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QTabBar:focus {\n"
"    border: 0px transparent black;\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    border-radius: 2px;\n"
"    background-image: url(icons/close_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"}\n"
"\n"
"QTabBar::close-button:hover {\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
"QTabBar::close-button:pressed {\n"
"    background-color: #adc5ed;\n"
"}\n"
"\n"
"QTabBar::scroller { /* the width of the scroll buttons */\n"
"    width: 20px;\n"
"}\n"
"\n"
"/* the scroll buttons are tool buttons */\n"
"QTabBar QToolButton,\n"
"QTabBar QToolButton:hover { \n"
"    margin-top: 4px;\n"
"    margin-bottom: 4px;\n"
"    margin-left: 0px;\n"
"    margin-right: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"    background-color: #e6e6e6;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled {\n"
"     image: url(icons/right_arrow_light.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled,\n"
"QTabBar QToolButton::right-arrow:off {\n"
"     image: url(icons/right_arrow_disabled_dark.png);\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:hover {\n"
"     image: url(icons/right_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:enabled {\n"
"     image: url(icons/left_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:disabled,\n"
" QTabBar QToolButton::left-arrow:off {\n"
"     image: url(icons/left_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::left-arrow:hover {\n"
"     image: url(icons/left_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:enabled {\n"
"     image: url(icons/up_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:disabled,\n"
" QTabBar QToolButton::up-arrow:off {\n"
"     image: url(icons/up_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::up-arrow:hover {\n"
"     image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:enabled {\n"
"     image: url(icons/down_arrow_light.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:disabled,\n"
" QTabBar QToolButton::down-arrow:off {\n"
"     image: url(icons/down_arrow_disabled_dark.png);\n"
"}\n"
"\n"
" QTabBar QToolButton::down-arrow:hover {\n"
"     image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"/* TOP and BOTTOM TABS */\n"
"QTabBar::tab:top,\n"
"QTabBar::tab:bottom {\n"
"    color: #ffffff;\n"
"    border: 1px solid #b6b6b6;\n"
"    border-left-color: #e6e6e6;\n"
"    border-right-width: 0px;\n"
"    background-color: #b6b6b6;\n"
"    padding:5px 15px;\n"
"    margin-top: 4px;\n"
"    margin-bottom: 4px;\n"
"    position: center;\n"
"}\n"
"\n"
"QTabBar::tab:top:first,\n"
"QTabBar::tab:bottom:first {\n"
"    border-top-left-radius: 6px;\n"
"    border-bottom-left-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:top:last,\n"
"QTabBar::tab:bottom:last {\n"
"    border-top-right-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    border-right-width: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected,\n"
"QTabBar::tab:bottom:selected {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover,\n"
"QTabBar::tab:bottom:!selected:hover {\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:top:only-one ,\n"
"QTabBar::tab:bottom:only-one {\n"
"    border: 1px solid #1b3774;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* LEFT and RIGHT TABS */\n"
"QTabBar::tab:left,\n"
"QTabBar::tab:right {\n"
"    color: #ffffff;\n"
"    border: 1px solid #b6b6b6;\n"
"    border-top-color: #e6e6e6;\n"
"    border-bottom-width: 0px;\n"
"    background-color: #b6b6b6;\n"
"    padding: 15px 5px;\n"
"    margin-left: 4px;\n"
"    margin-right: 4px;\n"
"    position: center;\n"
"}\n"
"\n"
"QTabBar::tab:left:first,\n"
"QTabBar::tab:right:first {\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:left:last,\n"
"QTabBar::tab:right:last {\n"
"    border-bottom-left-radius: 6px;\n"
"    border-bottom-right-radius: 6px;\n"
"    border-bottom-width: 1px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected,\n"
"QTabBar::tab:right:selected {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:0.545, y1:1, x2:0, y2:1, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover,\n"
"QTabBar::tab:right:!selected:hover {\n"
"    color: black;\n"
"}\n"
"\n"
"QTabBar::tab:left:only-one ,\n"
"QTabBar::tab:right:only-one {\n"
"    border: 1px solid #1b3774;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QDockWidget {\n"
"    color: #828282;\n"
"    border: 1px solid #e6e6e6;\n"
"    titlebar-close-icon: url(icons/close_dark.png);\n"
"    titlebar-normal-icon: url(icons/undock_dark.png);\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"    text-align: center;\n"
"    background-color: #e0e0e0;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QDockWidget::close-button,\n"
"QDockWidget::float-button {\n"
"    border: 1px transparent #e6e6e6;\n"
"    border-radius: 2px;\n"
"    background: transparent;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: right center;\n"
"}\n"
"\n"
"QDockWidget::close-button {\n"
"    right: 4px;\n"
"}\n"
"    \n"
"QDockWidget::float-button {\n"
"    right: 22px;\n"
"}\n"
"\n"
"QDockWidget::close-button:hover,\n"
"QDockWidget::float-button:hover {\n"
"    background: #f5f5f5;\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed,\n"
"QDockWidget::float-button:pressed {\n"
"    /*padding: 1px -1px -1px 1px;*/\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView {\n"
"    color: #828282;\n"
"    border: 1px solid #e6e6e6;\n"
"    border-radius: 4px;\n"
"    background-color: #bdc1c9;  /* related with alternate-background-color*/\n"
"    selection-color: black;\n"
"    selection-background-color: #5e90fa; /* should be similar to QListView::item selected background-color */\n"
"    show-decoration-selected: 1; /* make the selection span the entire width of the view */\n"
"    padding: 0px;\n"
"    margin: 0px 4px 0px 4px;\n"
"    min-width: 130px; /* hack to correctly align Preferences icon list  */\n"
"}\n"
"\n"
"QListView,\n"
"QListView::item,\n"
"QListView QAbstractItemView {\n"
"    margin: 0px;\n"
"    icon-size: 20px; /* temporal */\n"
"    paint-alternating-row-colors-for-empty-area: 1;\n"
"    position: absolute;\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: left top;\n"
"}\n"
"\n"
"/* Control dropdown list margins of QComboBox */\n"
"QComboBox QTreeView,\n"
"QComboBox QListView {\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QListView::item {\n"
"    border: 0px transparent #e6e6e6;\n"
"    border-radius: 4px;\n"
"    background-color: transparent;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"    display: inline-block;\n"
"    position: relative;\n"
"}\n"
"\n"
"QListView::item:selected,\n"
"QTreeView::item:selected  {\n"
"    color: black;\n"
"    background-color: #5e90fa; /* should be similar to QListView selection-background-color */\n"
"}\n"
"\n"
"/* Branch system */\n"
"QTreeView::branch  {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:!adjoins-item  {\n"
"    border-image: url(icons/branch_vline.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:has-siblings:adjoins-item  {\n"
"    border-image: url(icons/branch_more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:!has-children:!has-siblings:adjoins-item  {\n"
"    border-image: url(icons/branch_end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:closed:has-children:has-siblings  {\n"
"    image: url(icons/branch_closed_dark.png);\n"
"}\n"
"\n"
"QTreeView::branch:has-children:!has-siblings:closed  {\n"
"    image: url(icons/branch_closed_dark.png);\n"
"    border-image: url(icons/branch_end.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"    image: url(icons/branch_open_dark.png);\n"
"    border-image: url(icons/branch_more.png) 0;\n"
"}\n"
"\n"
"QTreeView::branch:open:has-children:!has-siblings  {\n"
"    image: url(icons/branch_open_dark.png);\n"
"    border-image: url(icons/branch_end.png) 0;\n"
"}\n"
"\n"
"QSlider,\n"
"QSlider:active,\n"
"QSlider:!active {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSlider:horizontal {\n"
"    padding: 0px 10px;\n"
"}\n"
"\n"
"QSlider:vertical {\n"
"    padding: 10px 0px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #b6b6b6;\n"
"    background-color: #b6b6b6;\n"
"    height: 8px;\n"
"    border-radius: 5px;\n"
"    margin: 4px 0;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border: 1px solid #b6b6b6;\n"
"    background-color: #b6b6b6;\n"
"    width: 8px;\n"
"    border-radius: 5px;\n"
"    margin: 4px 0;\n"
"}\n"
"\n"
"QSlider::groove:horizontal:disabled,\n"
"QSlider::groove:vertical:disabled {\n"
"    border-color:  #e0e0e0;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal,\n"
"QSlider::handle:vertical {\n"
"    background-color: #828282;\n"
"    border: 1px solid #828282;\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    margin: -4px 0;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    margin: 0 -4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover {\n"
"    border-color: #3874f2;\n"
"    background-color: #3874f2;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:pressed,\n"
"QSlider::handle:vertical:pressed {\n"
"    border-color: #1b3774;\n"
"    background-color: #1b3774;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled,\n"
"QSlider::handle:vertical:disabled {\n"
"    border-color: #b6b6b6;\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QToolButton {\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #b6b6b6, stop:1 #e6e6e6);\n"
"    border: 1px solid #828282;\n"
"    padding-top: 5px;\n"
"    padding-bottom: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"    margin-top: 5px;\n"
"    margin-bottom: 5px;\n"
"    margin-left: 10px;\n"
"    margin-right: 10px;\n"
"    border-radius: 3px;\n"
"    outline: none;\n"
"}\n"
"\n"
"QToolButton:hover,\n"
"QToolButton:focus {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QToolButton:disabled,\n"
"QToolButton:disabled:checked {\n"
"    color: #b6b6b6;\n"
"    background-color: #e6e6e6;\n"
"    border-color: #b6b6b6;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    border-color: #7cabf9;\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"    background-color: #5e90fa;\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QToolButton::menu-indicator  {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: center right;\n"
"    right: 4px;\n"
"}\n"
"\n"
"/*The \"show more\" button  (it can also be stylable with \"QToolBarExtension\" */\n"
"QToolButton#qt_toolbar_ext_button {\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    /*background-image: url(icons/more_dark.png);*/\n"
"    image: transparent;\n"
"    background-repeat: none;\n"
"    background-position: center left;\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button:hover {\n"
"    /*background-image: url(icons/more_light.png);*/\n"
"    border-color: #e0e0e0;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button:on {\n"
"    /*background-image: url(icons/more_light.png);*/\n"
"    border-color: #e0e0e0;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"\n"
"/*Buttons inside the Toolbar*/\n"
"QToolBar QToolButton {\n"
"    color: #828282;\n"
"    background-color: #e6e6e6;\n"
"    border: 1px transparent #e6e6e6;\n"
"    border-radius: 3px;\n"
"    margin: 0px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QToolBar QToolButton:disabled {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QToolBar QToolButton:checked {\n"
"    color: #1b3774;\n"
"    background-color: #5e90fa;\n"
"    border: 1px solid #5e90fa;\n"
"}\n"
"\n"
"QToolBar QToolButton:hover {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QToolBar QToolButton:pressed,\n"
"QToolBar QToolButton::menu-button:pressed {\n"
"    background-color: #e0e0e0;\n"
"    border: 1px solid #e0e0e0;\n"
"}\n"
"\n"
"\n"
"QToolBar QToolButton::menu-indicator:hover,\n"
"QToolBar QToolButton::menu-indicator:pressed {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* the subcontrols below are used only in the MenuButtonPopup mode */\n"
"QToolBar QToolButton::menu-button {\n"
"    border: 1px transparent #4A4949;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"    width: 16px; /* 16px width + 4px for border = 20px allocated above */\n"
"    outline: none;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolBar QToolButton::menu-button:hover,\n"
"QToolBar QToolButton::menu-button:active,\n"
"QToolBar QToolButton::menu-button:disabled {\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QToolBar QToolButton::menu-arrow {\n"
"    background-image: url(icons/down_arrow_light.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    height: 10px; /* same as arrow image */\n"
"}\n"
"\n"
"QToolBar QToolButton::menu-arrow:open {\n"
"    background-image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QToolBar:tear {\n"
"    color: blue;\n"
"    background-color: red;\n"
"}\n"
"\n"
"QTableView {\n"
"    color: #828282;\n"
"    border: 1px solid #b6b6b6;\n"
"    gridline-color: #f5f5f5;\n"
"    background-color: #bdc1c9;\n"
"    selection-color: #828282;\n"
"    selection-background-color: #adc5ed;\n"
"    border-radius: 3px;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QTableView::item:hover  {\n"
"    background: #abb0b7;\n"
"}\n"
"\n"
"QTableView::item:disabled  {\n"
"    color: #e6e6e6;\n"
"}\n"
"\n"
"QTableView::item:selected  {\n"
"    color: #1b3774;\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
"/* when editing a cell: */\n"
"QTableView QLineEdit {\n"
"    color: #828282;\n"
"    background-color: #b3b8bf;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    border: none;\n"
"    background-color: #828282;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section  {\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QHeaderView::section::vertical  {\n"
"    padding: 0px 6px 0px 6px;\n"
"    border-bottom: 1px solid #b6b6b6;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:first {\n"
"    border-top: 1px solid  #b6b6b6;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:last {\n"
"    border-bottom: none;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:only-one {\n"
"    border: none;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal  {\n"
"    padding: 0px 0px 0px 6px;\n"
"    border-right: 1px solid #b6b6b6;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:first {\n"
"    border-left: 1px solid #b6b6b6;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:last {\n"
"    border-left: none;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:only-one {\n"
"    border: none;\n"
"}\n"
"\n"
"QDockWidget QHeaderView::section {\n"
"    border-width: 6px 1px 6px 1px; /* hack to bigger margin for Model Panel table headers */\n"
"}\n"
"\n"
"QHeaderView::section:checked {\n"
"    color: #1b3774;\n"
"    background-color: #7cabf9;\n"
"}\n"
"\n"
" /* style the sort indicator */\n"
"QHeaderView::down-arrow {\n"
"    image: url(icons/down_arrow_light.png);\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"    image: url(icons/up_arrow_light.png);\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: #828282;\n"
"    border: 1px solid #828282;\n"
"    border-radius: 0px;\n"
"}\n"
"\n"
"QToolBox  {\n"
"    padding: 3px;\n"
"    color: #1b3774;\n"
"    border: none;\n"
"}\n"
"\n"
"QToolBox::tab { /* TODO */\n"
"    color: #ffffff;\n"
"    background-color: #b6b6b6;\n"
"    border: 1px transparent #828282;\n"
"    border-bottom: 1px transparent #b6b6b6;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QToolBox::tab:selected { /* italicize selected tabs */\n"
"    color: #1b3774;\n"
"    font: italic;\n"
"    background-color: #5e90fa;\n"
"    border-color: #5e90fa;\n"
" }\n"
"\n"
"QStatusBar::item {\n"
"    color: #ffffff;\n"
"    background-color: #e6e6e6;\n"
"    border: 1px solid #e6e6e6;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background-color: #e6e6e6;\n"
"    margin: 0px 11px;\n"
"    padding: 0px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    background-image: url(icons/splitter_horizontal_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    margin: 2px 10px 2px 10px;\n"
"    height: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    background-image: url(icons/splitter_horizontal_dark.png);\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"    margin: 10px 2px 10px 2px;\n"
"    width: 2px;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal:hover,\n"
"QSplitter::handle:vertical:hover {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"/* Similar to the splitter is the following window separator: */\n"
"QMainWindow::separator {\n"
"    border: 1px solid #e6e6e6;\n"
"    background-color: #e6e6e6;\n"
"    background-position: center center;\n"
"    background-repeat: none;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal {\n"
"    height: 4px;\n"
"    background-image: url(icons/splitter_horizontal_dark.png);\n"
"}\n"
"\n"
"QMainWindow::separator:vertical {\n"
"    width: 4px;\n"
"    background-image: url(icons/splitter_vertical_dark.png);\n"
"}\n"
"\n"
"QLabel {\n"
"    padding-top: 3px;\n"
"    padding-bottom: 3px;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #b6b6b6;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"/* Action group */\n"
"QFrame[class=\"panel\"] {\n"
"    border: none;\n"
"    background-color: #e6e6e6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] {\n"
"    border: none;\n"
"    background-color: #828282;\n"
"    border-top-left-radius: 3px;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"]:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"header\"] {\n"
"    text-align: left;\n"
"    font-weight: bold;\n"
"    color: #ffffff;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"header\"]:hover {\n"
"    color: black;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/down_arrow_light.png);\n"
"    background-repeat: none;\n"
"    background-position: center center;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel:hover {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/down_arrow_lighter.png);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel[fold=\"true\"] {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/up_arrow_light.png);\n"
"    background-repeat: none;\n"
"    background-position: center center;\n"
"    padding: 0px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"header\"] QLabel[fold=\"true\"]:hover {\n"
"    background-color: transparent;\n"
"    background-image: url(icons/up_arrow_lighter.png);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] {\n"
"    background-color: #bdc1c9;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"    border: none;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"/* HACK\n"
"This might not be the best way to reset the background color: */\n"
"QSint--ActionGroup QFrame[class=\"content\"] QWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #b6b6b6, stop:1 #e6e6e6);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:hover,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:focus {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:disabled:checked {\n"
"    color: #bdc1c9;\n"
"    border-color: #f5f5f5;\n"
"    background-color: #f5f5f5;\n"
"}\n"
"QSint--ActionGroup QFrame[class=\"content\"] QPushButton:checked {\n"
"    background-color: #5e90fa;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox {\n"
"    background-color: #b6b6b6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox:on {\n"
"    background-color: #b6b6b6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox QAbstractItemView {\n"
"    border-color: #828282;\n"
"    background-color: #828282;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QListView {\n"
"    border-color: #abb0b7;\n"
"    background-color: #abb0b7;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QAbstractSpinBox {\n"
"    background-color: #b6b6b6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QLineEdit {\n"
"    background-color: #b6b6b6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QComboBox:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QAbstractSpinBox:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QLineEdit:disabled {\n"
"    color: #bdc1c9;\n"
"    border-color: #f5f5f5;\n"
"    background-color: #f5f5f5;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QCheckBox:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QRadioButton:disabled {\n"
"    color: #f5f5f5;\n"
"    border-color: #f5f5f5;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QCheckBox::indicator:disabled,\n"
"QSint--ActionGroup QFrame[class=\"content\"] QRadioButton::indicator:disabled {\n"
"    border-color: #f5f5f5;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView {\n"
"    border: none;\n"
"    background-color: #828282;\n"
"    border-radius: 0px;\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section  {\n"
"    background-color: transparent;\n"
"    color: #ffffff;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 0px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal  {\n"
"    padding: 6px 0px 6px 6px;\n"
"    border-right: 1px solid #b6b6b6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal:first {\n"
"    border-left: 1px solid #e6e6e6;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal:last {\n"
"    border-left: none;\n"
"}\n"
"\n"
"QSint--ActionGroup QFrame[class=\"content\"] QHeaderView::section::horizontal:only-one {\n"
"    border: none;\n"
"}\n"
"/* enf of HACK */\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"],\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:enabled {\n"
"    font-weight: bold;\n"
"    color: #b6b6b6;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:hover,\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:enabled:hover {\n"
"    text-decoration: none;\n"
"    color: #828282;\n"
"    background-color: #abb0b7;\n"
"    border-color: #abb0b7;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:disabled {\n"
"    color: #e6e6e6;\n"
"    background-color: #abb0b7;\n"
"    border-color: #abb0b7;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:focus,\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:pressed\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:enabled:focus,\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:enabled:pressed {\n"
"    color: black;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.545, x2:1, y2:0, stop:0 #3874f2, stop:1 #5e90fa);\n"
"    border-color: #3874f2;\n"
"}\n"
"\n"
"QSint--ActionGroup QToolButton[class=\"action\"]:on {\n"
"    background-color: red;\n"
"    color: red;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(-10, 10, 331, 361))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 338, 311))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lneTck = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneTck.setMaxLength(11)
        self.lneTck.setObjectName("lneTck")
        self.horizontalLayout.addWidget(self.lneTck)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lneAd = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneAd.setObjectName("lneAd")
        self.horizontalLayout_2.addWidget(self.lneAd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lneSoyad = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneSoyad.setObjectName("lneSoyad")
        self.horizontalLayout_3.addWidget(self.lneSoyad)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.lneIkametgah = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneIkametgah.setObjectName("lneIkametgah")
        self.horizontalLayout_5.addWidget(self.lneIkametgah)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(330, 10, 481, 361))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tblwBilgiler = QtWidgets.QTableWidget(self.centralwidget)
        self.tblwBilgiler.setGeometry(QtCore.QRect(0, 390, 951, 181))
        self.tblwBilgiler.setRowCount(100)
        self.tblwBilgiler.setColumnCount(9)
        self.tblwBilgiler.setObjectName("tblwBilgiler")
        self.lblKayitSayisi = QtWidgets.QLabel(self.centralwidget)
        self.lblKayitSayisi.setGeometry(QtCore.QRect(170, 590, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblKayitSayisi.setFont(font)
        self.lblKayitSayisi.setText("")
        self.lblKayitSayisi.setObjectName("lblKayitSayisi")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 580, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(820, 40, 121, 321))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnekle = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btnekle.setFont(font)
        self.btnekle.setObjectName("btnekle")
        self.verticalLayout_3.addWidget(self.btnekle)
        self.btnsil = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btnsil.setFont(font)
        self.btnsil.setObjectName("btnsil")
        self.verticalLayout_3.addWidget(self.btnsil)
        self.btnara = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btnara.setFont(font)
        self.btnara.setObjectName("btnara")
        self.verticalLayout_3.addWidget(self.btnara)
        self.btnguncelle = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btnguncelle.setFont(font)
        self.btnguncelle.setObjectName("btnguncelle")
        self.verticalLayout_3.addWidget(self.btnguncelle)
        self.btnlistele = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btnlistele.setFont(font)
        self.btnlistele.setObjectName("btnlistele")
        self.verticalLayout_3.addWidget(self.btnlistele)
        self.btncikis = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.btncikis.setFont(font)
        self.btncikis.setObjectName("btncikis")
        self.verticalLayout_3.addWidget(self.btncikis)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(330, 60, 463, 311))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.cmbUrun = QtWidgets.QComboBox(self.layoutWidget2)
        self.cmbUrun.setEnabled(True)
        self.cmbUrun.setEditable(False)
        self.cmbUrun.setCurrentText("")
        self.cmbUrun.setObjectName("cmbUrun")
        self.cmbUrun.addItem("")
        self.cmbUrun.addItem("")
        self.cmbUrun.addItem("")
        self.cmbUrun.addItem("")
        self.cmbUrun.addItem("")
        self.cmbUrun.addItem("")
        self.cmbUrun.addItem("")
        self.cmbUrun.addItem("")
        self.horizontalLayout_7.addWidget(self.cmbUrun)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_7)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_9.addWidget(self.label_12)
        self.spnBirim = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spnBirim.setObjectName("spnBirim")
        self.horizontalLayout_9.addWidget(self.spnBirim)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.spnMiktar = QtWidgets.QSpinBox(self.layoutWidget2)
        self.spnMiktar.setObjectName("spnMiktar")
        self.horizontalLayout_8.addWidget(self.spnMiktar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.clntarih = QtWidgets.QCalendarWidget(self.layoutWidget2)
        self.clntarih.setObjectName("clntarih")
        self.horizontalLayout_10.addWidget(self.clntarih)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 952, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.cmbUrun.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "        KİMLİK BİLGİLERİ"))
        self.label.setText(_translate("MainWindow", "TC Kimlik Numarası:"))
        self.label_2.setText(_translate("MainWindow", "Adı:"))
        self.label_3.setText(_translate("MainWindow", "Soyadı:"))
        self.label_5.setText(_translate("MainWindow", "İkametgah:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "ÜRÜN BİLGİLERİ"))
        self.label_10.setText(_translate("MainWindow", "Toplam Kayıt Sayısı:"))
        self.btnekle.setText(_translate("MainWindow", "KAYIT EKLE"))
        self.btnsil.setText(_translate("MainWindow", "KAYIT SİL"))
        self.btnara.setText(_translate("MainWindow", "KAYIT ARA"))
        self.btnguncelle.setText(_translate("MainWindow", "GÜNCELLE"))
        self.btnlistele.setText(_translate("MainWindow", "KAYIT LİSTELE"))
        self.btncikis.setText(_translate("MainWindow", "ÇIKIŞ"))
        self.label_6.setText(_translate("MainWindow", "Ürün "))
        self.cmbUrun.setItemText(0, _translate("MainWindow", "Arpa"))
        self.cmbUrun.setItemText(1, _translate("MainWindow", "Ayçiçeği"))
        self.cmbUrun.setItemText(2, _translate("MainWindow", "Buğday"))
        self.cmbUrun.setItemText(3, _translate("MainWindow", "Fıstık"))
        self.cmbUrun.setItemText(4, _translate("MainWindow", "Kanola"))
        self.cmbUrun.setItemText(5, _translate("MainWindow", "Mısır"))
        self.cmbUrun.setItemText(6, _translate("MainWindow", "Pirinç"))
        self.cmbUrun.setItemText(7, _translate("MainWindow", "Zeytin"))
        self.label_12.setText(_translate("MainWindow", "Birim Fiyat"))
        self.label_7.setText(_translate("MainWindow", "Miktar(kg)"))
        self.label_8.setText(_translate("MainWindow", "Ürün Alım Tarihi:"))

